#!/usr/bin/env python3
"""Build a working scoring package you can upload and run.

Writing one by hand is where the mistakes are. The demo package shipped with a
manifest that declared eight metrics its script never produced, because the
manifest listed per-file names while the pipeline reads the run summary. It
looked fine until it was run, and then failed with a message about missing
metrics that told you nothing about the cause.

This generates the pair together, so the manifest can only ever declare what
the script emits: the metric names come from one list used to write both.

    python3 scripts/make_example_scoring_package.py --challenge asl
    python3 scripts/make_example_scoring_package.py --challenge dce --with-masks
    python3 scripts/make_example_scoring_package.py --challenge dsc
    python3 scripts/make_example_scoring_package.py --challenge asl --out my.zip

The generated package computes real numbers from the submitted maps, and with
--with-masks reports them inside each ROI as well. It is a starting point to
edit, not official scoring, and says so in its own output.

No real or private data is involved. Nothing is written outside the output path.
"""

from __future__ import annotations

import argparse
import json
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(REPO_ROOT / "src")]

#: The single source of truth for what this package reports. The manifest and
#: the script are both written from this, so they cannot disagree.
SUMMARY_METRICS = (
    "file_count",
    "readable_file_count",
    "mean_finite_percent",
    "mean_negative_percent",
    "mean_of_map_means",
)

#: Reported only when masks are supplied. Kept separate because a metric that
#: is sometimes absent must not be declared unconditionally: the pipeline reads
#: a declared-but-null metric as one the package failed to produce, which is
#: exactly how the shipped demo package came to fail.
MASK_METRICS = (
    "roi_count",
    "mean_roi_mean",
)

SCRIPT = '''#!/usr/bin/env python3
"""{title}

Generated by scripts/make_example_scoring_package.py. Edit freely.

Reads every NIfTI in the submission, reports simple per-map statistics, and
summarises them. Not official OSIPI scoring, and it says so in its output.

The pipeline reads the ``summary`` object below and checks that every metric
named in manifest.json is present in it with a value. Add a metric to both, or
neither.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

PACKAGE_NAME = {name!r}
PACKAGE_VERSION = {version!r}
OFFICIAL_OSIPI_SCORING = False

USE_MASKS = {use_masks}


def read_map(path):
    """Voxels as float64, or None when the file will not open.

    nibabel is imported here rather than at module scope on purpose. The
    pipeline validates an uploaded package by importing its entry point in an
    isolated interpreter, which does not see user-installed packages. A
    top-level import therefore rejects a perfectly good package on any machine
    where nibabel is installed for the user rather than system-wide.
    """
    try:
        import nibabel as nib  # noqa: PLC0415
        return np.asarray(nib.load(str(path)).dataobj, dtype=np.float64)
    except Exception:
        return None


def load_masks(reference_dir):
    """Boolean masks from a reference directory, by name."""
    masks = {{}}
    if not reference_dir:
        return masks
    for candidate in sorted(Path(reference_dir).rglob("*mask*.nii*")):
        data = read_map(candidate)
        if data is not None:
            masks[candidate.name.split(".")[0]] = data > 0.5
    return masks


def score_file(path, submission_dir, masks):
    data = read_map(path)
    relative = str(path.relative_to(submission_dir))
    if data is None:
        return {{"file": relative, "status": "unreadable"}}

    finite = np.isfinite(data)
    values = data[finite]
    row = {{
        "file": relative,
        "status": "ok",
        "voxel_count": int(data.size),
        "finite_percent": float(100.0 * finite.sum() / data.size) if data.size else 0.0,
        "negative_percent": float(100.0 * (values < 0).sum() / values.size) if values.size else 0.0,
        "mean": float(values.mean()) if values.size else None,
    }}
    if USE_MASKS and masks:
        rois = {{}}
        for label, mask in masks.items():
            if mask.shape != data.shape:
                continue
            inside = data[mask & finite]
            if inside.size:
                rois[label] = {{"voxel_count": int(inside.size),
                              "mean": float(inside.mean())}}
        row["rois"] = rois
    return row


def summarise(rows):
    ok = [r for r in rows if r.get("status") == "ok"]

    def average(key):
        values = [r[key] for r in ok if r.get(key) is not None]
        return float(np.mean(values)) if values else None

    summary = {{
        "package": PACKAGE_NAME,
        "package_version": PACKAGE_VERSION,
        "official_osipi_scoring": OFFICIAL_OSIPI_SCORING,
        "status": "completed" if len(ok) == len(rows) else "completed_with_errors",
        "file_count": len(rows),
        "readable_file_count": len(ok),
        "mean_finite_percent": average("finite_percent") or 0.0,
        "mean_negative_percent": average("negative_percent") or 0.0,
        "mean_of_map_means": average("mean") or 0.0,
        "notes": ["Example package. Not official OSIPI scoring."],
    }}

    if USE_MASKS:
        roi_means, labels = [], set()
        for row in ok:
            for label, stats in (row.get("rois") or {{}}).items():
                labels.add(label)
                roi_means.append(stats["mean"])
        # Always a number, never null: a declared metric with no value reads to
        # the pipeline as one the package failed to produce.
        summary["roi_count"] = len(labels)
        summary["mean_roi_mean"] = float(np.mean(roi_means)) if roi_means else 0.0

    return summary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--submission-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--reference-dir", default=None)
    args = parser.parse_args()

    submission_dir = Path(args.submission_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    masks = load_masks(args.reference_dir)
    files = [p for p in sorted(submission_dir.rglob("*"))
             if p.is_file() and p.name.lower().endswith((".nii", ".nii.gz"))
             and not p.name.startswith(".")]
    rows = [score_file(p, submission_dir, masks) for p in files]
    summary = summarise(rows)

    if not files:
        summary["status"] = "failed"
        summary["notes"].append("No NIfTI files were found in the submission.")

    (output_dir / "metrics.json").write_text(
        json.dumps({{"summary": summary, "per_file": rows}}, indent=2), encoding="utf-8")
    (output_dir / "results.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8")

    print(json.dumps(summary, indent=2))
    return 0 if summary["status"] != "failed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
'''

README = """# {title}

Generated by `scripts/make_example_scoring_package.py`.

**Not official OSIPI scoring.** A working starting point to edit.

## What it reports

{metric_list}

## The rule that matters

`manifest.json` declares metric names. The pipeline reads the `summary` object
your script prints and refuses the run if any declared metric is missing or
null. Add a metric to both files, or to neither.

A metric that is only sometimes available must not be declared: the pipeline
cannot tell "not applicable this time" from "the package failed to produce it".

## Editing

`scoring.py` receives `--submission-dir`, `--output-dir` and, when the
challenge has reference data, `--reference-dir`. Write `results.json` with your
summary and print it. Everything else is yours to change.
"""


def build(challenge: str, use_masks: bool, out: Path) -> Path:
    metrics = list(SUMMARY_METRICS) + (list(MASK_METRICS) if use_masks else [])
    suffix = "_masks" if use_masks else ""
    package_id = f"{challenge}_example{suffix}"
    title = f"{challenge.upper()} example scoring package"

    from osipi_pipeline.config.rules import required_maps_by_challenge

    configured_maps = required_maps_by_challenge()
    if challenge not in configured_maps:
        available = ", ".join(sorted(configured_maps))
        raise ValueError(
            f"Unknown challenge {challenge!r}. Configured challenges: {available}"
        )
    required = list(configured_maps[challenge])

    manifest = {
        "package_id": package_id,
        "name": title,
        "version": "1.0.0",
        "challenge_type": challenge,
        "map_type": "",
        "description": f"Example {challenge.upper()} package. Not official OSIPI scoring.",
        "metrics": metrics,
        # Taken from the challenge's own configuration rather than typed here,
        # so the package cannot declare an input the challenge does not define.
        "required_inputs": required,
        "entry_point": "scoring.py",
        "call_mode": "standard",
        "official": False,
        "expected_input_pattern": "*.nii*",
    }

    script = SCRIPT.format(title=title, name=title, version="1.0.0",
                           use_masks=repr(use_masks))
    readme = README.format(
        title=title,
        metric_list="\n".join(f"- `{m}`" for m in metrics))

    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", json.dumps(manifest, indent=2) + "\n")
        zf.writestr("scoring.py", script)
        zf.writestr("README.md", readme)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--challenge", default="asl",
                        help="Challenge id from validation_rules.yaml")
    parser.add_argument("--with-masks", action="store_true",
                        help="Also report statistics inside each reference ROI")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    challenge = args.challenge.strip().lower()
    suffix = "_masks" if args.with_masks else ""
    out = args.out or (REPO_ROOT / "data" / "scoring" / "examples"
                       / f"{challenge}_example{suffix}.zip")
    try:
        build(challenge, args.with_masks, out)
    except ValueError as exc:
        parser.error(str(exc))

    metrics = list(SUMMARY_METRICS) + (list(MASK_METRICS) if args.with_masks else [])
    print(f"\n  {out}")
    print(f"  challenge {challenge}, {len(metrics)} metrics"
          f"{', ROI statistics included' if args.with_masks else ''}")
    print("  Upload it in Reviewer settings, Active Analysis Provider,"
          " Upload Package ZIP.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
