#!/usr/bin/env python3
"""Build the smallest submission a challenge will accept, for a quick try.

The archives in ``submissions/incoming/`` are realistic, which makes them slow
to reason about when all you want is to press the buttons once and watch what
happens. This writes the smallest thing that still exercises the whole
pipeline, with a few voxels per map, so a pass through Upload, Review,
Validate, Run, QC and Export takes seconds and every number on screen is small
enough to check by hand.

    python3 scripts/make_minimal_submission.py

What "smallest" means depends on the challenge, and the script reads that from
the configuration rather than assuming it:

  ASL and DSC declare no dataset grid, so one scan holding the required maps
  validates cleanly. ASL is the default for exactly that reason.

  DCE declares a grid, five participants by two repeats for the clinical
  dataset, and requires a modelled signal-time curve alongside the maps. A
  single DCE scan therefore cannot pass, and the script says so instead of
  claiming otherwise. Pass --complete to build the full declared grid.

Options:
    --challenge asl|dce|dsc   Default asl, the smallest clean pass.
    --complete                Build whatever the challenge declares, grid and
                              required artifacts included, so validation
                              passes. Larger, still small.
    --maps cbf,att            Override which maps to include.
    --out PATH                Write somewhere else.

Nothing here is imaging data: the voxel values are a fixed ramp.
"""

from __future__ import annotations

import argparse
import sys
import tempfile
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(REPO_ROOT / "src")]

from osipi_pipeline.config.rules import (  # noqa: E402
    challenge_types,
    datasets_by_challenge,
    required_artifacts_by_challenge,
    required_maps_by_challenge,
)
from osipi_pipeline.testing.synthetic import (  # noqa: E402
    VOLUME_VALUES,
    write_nifti,
)

#: Fallback when a dataset declares a count as null, meaning "pending a
#: decision from the challenge leads". One keeps the archive small and is
#: never wrong in a way that matters here.
PENDING_COUNT = 1


def _scans(challenge: str, complete: bool) -> list[tuple[str, int, int, int]]:
    """Which (dataset, participant, site, repeat) scans to write.

    Without ``complete`` this is deliberately one scan, whatever the challenge
    declares, because seeing the count mismatch reported is itself a useful
    thing to look at.
    """
    grid = datasets_by_challenge().get(challenge) or {}
    if not grid:
        return [("Clinical", 1, 1, 1)]
    if not complete:
        first = sorted(grid)[0]
        return [(first.capitalize(), 1, 1, 1)]

    scans: list[tuple[str, int, int, int]] = []
    for dataset in sorted(grid):
        counts = grid[dataset] or {}
        participants = counts.get("participants") or PENDING_COUNT
        repeats = counts.get("repeats") or PENDING_COUNT
        sites = counts.get("sites") or PENDING_COUNT
        for participant in range(1, int(participants) + 1):
            for site in range(1, int(sites) + 1):
                for repeat in range(1, int(repeats) + 1):
                    scans.append((dataset.capitalize(), participant, site, repeat))
    return scans


def build(challenge: str, maps: list[str], scans, artifacts, destination: Path) -> Path:
    """Write the submission and zip it."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp) / f"minimal_{challenge}"
        for dataset, participant, site, repeat in scans:
            scan = (root / dataset / f"Participant{participant}"
                    / f"Site{site}" / f"Repeat{repeat}")
            for name in maps:
                write_nifti(scan / f"{name}.nii.gz")
            if "modelled_st" in artifacts:
                # A signal-time curve varies over time, so it is 4-D where the
                # parameter maps are 3-D.
                write_nifti(scan / "modelled_st.nii.gz",
                            VOLUME_VALUES * 2, (2, 2, 2, 2))
        if "methods" in artifacts:
            (root / "methods.txt").write_text(
                "Minimal submission generated by "
                "scripts/make_minimal_submission.py for trying the pipeline "
                "end to end. Not real data.\n",
                encoding="utf-8",
            )
        destination.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
            for path in sorted(root.rglob("*")):
                if path.is_file():
                    archive.write(path, path.relative_to(root.parent))
    return destination


def main(argv: list[str] | None = None) -> int:
    known = sorted(challenge_types())
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--challenge", default="asl", choices=known)
    parser.add_argument("--complete", action="store_true",
                        help="Build the full declared grid so validation passes")
    parser.add_argument("--maps", default=None, help="Comma separated map ids")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    challenge = args.challenge.lower()
    required = list(required_maps_by_challenge().get(challenge) or [])
    maps = ([item.strip() for item in args.maps.split(",") if item.strip()]
            if args.maps else required)
    if not maps:
        print(f"{challenge} declares no required maps. Pass --maps to choose "
              f"some.", file=sys.stderr)
        return 1

    artifacts = tuple(required_artifacts_by_challenge().get(challenge) or ())
    # Without --complete the point is to stay at one scan, so a required
    # per-scan artifact is left out and reported by validation.
    included = artifacts if args.complete else tuple(
        name for name in artifacts if name == "methods"
    )
    scans = _scans(challenge, args.complete)
    grid = datasets_by_challenge().get(challenge) or {}

    suffix = "complete" if args.complete else "minimal"
    destination = args.out or (
        REPO_ROOT / "submissions" / "incoming" / f"{suffix}_{challenge}.zip"
    )
    build(challenge, maps, scans, included, destination)

    try:
        shown = destination.relative_to(Path.cwd())
    except ValueError:
        shown = destination
    print(f"Wrote {shown} ({destination.stat().st_size / 1024:.1f} KB)")
    print(f"  challenge : {challenge}")
    print(f"  maps      : {', '.join(maps)}")
    print(f"  scans     : {len(scans)}")

    if args.complete or not grid:
        missing = [name for name in artifacts if name not in included]
        if missing:
            print(f"  expect    : validation will report {', '.join(missing)} "
                  f"as missing.")
        else:
            print("  expect    : validation passes, no errors.")
    else:
        print(f"  expect    : validation will report count mismatches, because "
              f"{challenge} declares a dataset grid and this is one scan. That "
              f"is worth seeing once. Use --complete for a clean pass.")
    print(f"\nUpload it at http://localhost:8000 and pick the "
          f"{challenge.upper()} challenge.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
